In [3]:
import pandas as pd
df = pd.read_csv("dataset/digit_recognizer/train.csv")

In [4]:
df.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [8]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\Vanilla\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [9]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.853452380952381

In [11]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [12]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

     0    1    2    3    4    5    6    7    8    9
0  754    1   12    7    6   17    8    6    8    2
1    1  895   11    6    9    3    4    9   22    2
2   10   24  663   37   16   13   18   20   20    8
3   11   11   27  702    5   43   11   12   24   18
4    7    5   13    5  731    6   13    7   19   50
5   12    9   14   35    4  576   25    8   31   15
6   10    2    9    4   13   19  762    0   15    5
7    5    8   23   10    9    5    1  778   10   24
8   15   13   25   32   17   26   11    5  622   27
9    8    5    7   14   45   16    4   24   25  686

In [25]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [32]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [33]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [34]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400