In [8]:
import pandas as pd

df = pd.read_csv('dataset/heart_disease_data.csv')

In [9]:
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,48,1,0,130,256,1,0,150,1,0.0,2,2,3,0
1,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
2,44,0,2,118,242,0,1,149,0,0.3,1,1,2,1
3,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
4,56,1,3,120,193,0,0,162,0,1.9,1,0,3,1
5,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
6,63,1,0,130,254,0,0,147,0,1.4,1,1,3,0
7,35,1,0,126,282,0,0,156,1,0.0,2,0,3,0
8,66,1,0,120,302,0,0,151,0,0.4,1,0,2,1
9,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [12]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [13]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\Vanilla\anaconda3\envs\myenv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [14]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8524590163934426
Accuracy of Decision Trees 0.9180327868852459

In [16]:
confusion_matrix(y_test,y_pred1)

array([[44, 14],
       [ 4, 60]])

In [17]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix

    0   1
0  44  14
1   4  60

In [18]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix

    0   1
0  52   6
1   4  60

In [19]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [20]:
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
221             0                               0                         0
397             0                               1                         1
40              1                               1                         1
448             1                               1                         1
240             0                               1                         0
123             1                               1                         1
409             1                               1                         1
194             1                               1                         1
146             1                               1                         1
108             1                               1                         1

### Precision, Recall and F1 Score

In [21]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [22]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  44  14
1   4  60
--------------------------------------------------
Precision -  0.8108108108108109
Recall -  0.9375
F1 score -  0.8695652173913043

In [23]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1
0  52   6
1   4  60
--------------------------------------------------
Precision -  0.9090909090909091
Recall -  0.9375
F1 score -  0.9230769230769231

#### getting precision, recall for both [0, 1] labels simulataneously

In [24]:
precision_score(y_test,y_pred1,average=None)

array([0.91666667, 0.81081081])

In [25]:
precision_score(y_test,y_pred2,average=None)

array([0.92857143, 0.90909091])

In [27]:
recall_score(y_test,y_pred1,average=None)

array([0.75862069, 0.9375    ])

In [28]:
recall_score(y_test,y_pred1,average=None)

array([0.75862069, 0.9375    ])